spring.application.name=examination-portal-backend

spring.datasource.url=jdbc:mysql://localhost:3306/examination_portal
spring.datasource.username=root
spring.datasource.password=your_db_pwd

spring.jpa.hibernate.ddl-auto=update